name: Release Tag

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set tag env
      run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker Build and Save
      run: |
        docker build -t shelang/jolo:$TAG_VERSION -f Dockerfile .
        docker save shelang/jolo:$TAG_VERSION > shelang-jolo-$TAG_VERSION.docker.tar.gz
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        generate_release_notes: true
        files: |
          *.docker.tar.gz
